# Generated by Django 4.2.4 on 2023-08-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_remove_projectmodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmodel",
            name="slug",
            field=models.SlugField(default="sd"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateField(auto_now=True)),
                ("date_due", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("p", "Pending"), ("c", "Completed")],
                        default="p",
                        max_length=1,
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.projectmodel",
                        verbose_name="sdfs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubTaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateField(auto_now=True)),
                ("date_due", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("p", "Pending"), ("c", "Completed")],
                        default="p",
                        max_length=1,
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="projects.taskmodel",
                    ),
                ),
            ],
        ),
    ]
