# Generated by Django 4.2.4 on 2023-09-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_projectmodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmodel",
            name="importance",
            field=models.CharField(
                choices=[("h", "High"), ("m", "Medium"), ("l", "Low")],
                default="m",
                max_length=1,
                null=True,
            ),
        ),
    ]
