# Generated by Django 4.2.4 on 2023-08-23 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_projectmodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtaskmodel",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="projects.taskmodel",
                verbose_name="Task",
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.projectmodel",
                verbose_name="Project",
            ),
        ),
    ]
