# Generated by Django 4.2.4 on 2023-08-23 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_subtaskmodel_task_alter_taskmodel_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectmodel",
            options={"verbose_name": "Project", "verbose_name_plural": "Projects"},
        ),
        migrations.AlterModelOptions(
            name="subtaskmodel",
            options={"verbose_name": "SubTask", "verbose_name_plural": "SubTasks"},
        ),
        migrations.AlterModelOptions(
            name="taskmodel",
            options={"verbose_name": "Task", "verbose_name_plural": "Tasks"},
        ),
    ]
