# Generated by Django 4.2.4 on 2023-08-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_projectmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmodel",
            name="date_due",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date Due"),
        ),
    ]
