# Generated by Django 4.2.4 on 2023-08-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_alter_projectmodel_date_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtaskmodel",
            name="date_due",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date Due"),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="date_due",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date Due"),
        ),
    ]
