# Generated by Django 4.2.4 on 2023-08-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_alter_subtaskmodel_date_due_alter_taskmodel_date_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmodel",
            name="date_due",
            field=models.DateField(blank=True, null=True, verbose_name="Date Due"),
        ),
    ]
