# Generated by Django 4.2.4 on 2023-08-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_alter_projectmodel_date_due"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmodel",
            name="date_updated",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="subtaskmodel",
            name="date_updated",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="date_updated",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="date_created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="date_due",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date Due"),
        ),
        migrations.AlterField(
            model_name="subtaskmodel",
            name="date_created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="date_created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
