# Generated by Django 4.2.4 on 2023-08-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0010_projectmodel_date_updated_subtaskmodel_date_updated_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmodel",
            name="date_due",
            field=models.DateField(blank=True, null=True, verbose_name="Date Due"),
        ),
        migrations.AlterField(
            model_name="subtaskmodel",
            name="date_due",
            field=models.DateField(blank=True, null=True, verbose_name="Date Due"),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="date_due",
            field=models.DateField(blank=True, null=True, verbose_name="Date Due"),
        ),
    ]
