# Generated by Django 4.2.4 on 2023-08-23 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0012_projectmodel_task_alter_projectmodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmodel",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_projects",
                to="projects.taskmodel",
                verbose_name="Task",
            ),
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
