# Generated by Django 4.2.4 on 2023-08-23 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_alter_projectmodel_task_alter_projectmodel_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmodel",
            name="task",
        ),
    ]
