# Generated by Django 4.2.4 on 2023-09-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=50, null=True, verbose_name="first name"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="surname",
            field=models.CharField(max_length=50, null=True, verbose_name="surname"),
        ),
    ]
