# Generated by Django 4.2.4 on 2023-08-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_pfp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="pfp",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/",
                verbose_name="profile picture",
            ),
        ),
    ]
