# Generated by Django 4.2.4 on 2023-08-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_customuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="s", max_length=50, verbose_name="username"),
            preserve_default=False,
        ),
    ]
