# Generated by Django 4.2.4 on 2023-09-07 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_first_name_customuser_surname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="surname",
            new_name="last_name",
        ),
    ]
