# Generated by Django 4.2.4 on 2023-08-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=50, unique=True, verbose_name="username"),
        ),
    ]
