# Generated by Django 4.2.4 on 2023-08-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_projectmodel_slug_taskmodel_subtaskmodel"),
        ("accounts", "0008_customuser_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="projects",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="projects.projectmodel",
                verbose_name="Projects",
            ),
        ),
    ]
